<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function myportal_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.myportal_breadcrumb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Setting breadcrumbs for website') . '</p>';
      return $output;

    default:
  }

}
